@startuml User sign-up

FRT -> API: POST /auth/register {email, password}
API -> API: rqst.validate(RegisterValidator)
alt success
API -> DTB: new User() // email_validated: false
API -> DTB: new Token() // EMAIL_VALIDATION
API -> FRT: (Send mail with link)
else error
API -> FRT: E_VALIDATION_ERROR
end
@enduml